# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: COS 126 Spring 2025 # Website name
baseurl: "https://www.cs.princeton.edu/courses/archive/spr25/cos126/" # Website URL
params:
  tigerfileurl: "https://tigerfile.cs.princeton.edu/COS126_S2025"
  edurl: "https://edstem.org/us/courses/71961/discussion/"
  edlessonsurl: "https://edstem.org/us/courses/71961/lessons"
  iclickerSem: "COS 126 Spring'25"
  surveyurl: "https://forms.cs50.io/7065a46c-1c70-44e1-ad8b-883628d98a4f"
  midsemestersurveyurl: "https://forms.cs50.io/69655318-223d-4b71-8518-37f5ae69b12c"
  semester: "SPRING"

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
